
package br.ifrn.queiroga.aplicacao;

import br.ifrn.queiroga.model.Categoria;
import br.ifrn.queiroga.model.CategoriaDAO;
import br.ifrn.queiroga.dao.PessoaDAO;
import br.ifrn.queiroga.model.Livro;
import br.ifrn.queiroga.model.Pessoa;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class Listagem extends javax.swing.JFrame {
    
    public List<Pessoa> oficial = new ArrayList<Pessoa>();
    public static List<Categoria> listinha = new ArrayList<Categoria>();
    
    public static void table(javax.swing.JTable tabela){
            DefaultTableModel modelo
                = new javax.swing.table.DefaultTableModel();
        PessoaDAO pDAO = new PessoaDAO();
        CategoriaDAO dao = new CategoriaDAO();
        listinha = dao.getAll();
        List<Pessoa> lista2 = pDAO.getAll();
        
        String [] Colunas = {"Nome", "Apelido", "E-mail", "Telefone", "Data de Nascimento", "Categoria"};
        modelo = new DefaultTableModel(null,Colunas);
       
        
        for (Pessoa p : lista2){
            if (p != null){                
                modelo.addRow(new Object[]{
                    p.getNome(),
                    p.getApelido(),
                    p.getEmail(),
                    p.getTelefone(),
                    p.getNasc(),
                    listinha.get(p.getCategoria()).getNome()}
                );
             
            }
        }
         tabela.setModel(modelo);
     
    }
    
    public Listagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JTable();
        nomePesq = new javax.swing.JTextField();
        Pesq = new javax.swing.JButton();
        Deletar = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Apelido", "E-mail", "Telefone", "Data de Nascimento", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(lista);

        nomePesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePesqActionPerformed(evt);
            }
        });

        Pesq.setText("Pesquisar");
        Pesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesqActionPerformed(evt);
            }
        });

        Deletar.setText("Deletar");
        Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarActionPerformed(evt);
            }
        });

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        jButton1.setText("Listar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel8.setText("__");

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel6.setText("LISTAGEM");

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel7.setText("__");

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(nomePesq, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47)
                                    .addComponent(Pesq, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomePesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pesq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deletar)
                    .addComponent(Editar)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomePesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePesqActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       table(lista);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarActionPerformed
        PessoaDAO X = new PessoaDAO();
        List<Pessoa> aux = X.getAll();
        Pessoa p1 = new Pessoa();
        
        p1 = aux.get(lista.getSelectedRow());
        
        X.delete(p1.getId());
        
        table(lista);
    }//GEN-LAST:event_DeletarActionPerformed
    
    boolean edit = false;
    int aux2 = 0;
    
    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        
        Edicao2 c = new Edicao2();
        Edicao2.edit = true;
        PessoaDAO pD = new PessoaDAO();
        List<Pessoa> aux = pD.getAll();
        Pessoa p = new Pessoa();
        
        if(!Edicao2.pesq){
            p = aux.get(lista.getSelectedRow());
            Edicao2.id = lista.getSelectedRow();

            Edicao2.nome.setText(p.getNome());
            Edicao2.apel.setText(p.getApelido());
            Edicao2.nasc.setText(p.getNasc());
            Edicao2.email.setText(p.getEmail());
            Edicao2.fone.setText(p.getTelefone());
            
            Edicao2.categ.setSelectedIndex(p.getCategoria());
            System.out.println(p.getCategoria());
            
        }else{
            p = oficial.get(lista.getSelectedRow());
            Edicao2.id = lista.getSelectedRow();
            Edicao2.nome.setText(p.getNome());
            Edicao2.apel.setText(p.getApelido());
            Edicao2.nasc.setText(p.getNasc());
            Edicao2.email.setText(p.getEmail());
            Edicao2.fone.setText(p.getTelefone());
            Edicao2.categ.setSelectedIndex(p.getCategoria());
            
        }
        
        c.setVisible(true);

    }//GEN-LAST:event_EditarActionPerformed

    private void PesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesqActionPerformed
       DefaultTableModel modelo
                = new javax.swing.table.DefaultTableModel();
       String name = nomePesq.getText();
       PessoaDAO Z = new PessoaDAO();
       oficial = Z.getByName(name);
       CategoriaDAO daoz = new CategoriaDAO();
       listinha = daoz.getAll();
       
       String [] Colunas = {"Nome", "Apelido", "E-mail", "Telefone", "Data de Nascimento", "Categoria"};
        modelo = new DefaultTableModel(null,Colunas);
       String res = null;
       
       
        
        for (Pessoa p : oficial){
            
            
            if (p != null){ 
                
                
                modelo.addRow(new Object[]{
                    p.getNome(),
                    p.getApelido(),
                    p.getEmail(),
                    p.getTelefone(),
                    p.getNasc(),
                    listinha.get(p.getCategoria() + 1)
                    }
                );
             
            }
        }
         lista.setModel(modelo);
         Edicao2.pesq = true;
    }//GEN-LAST:event_PesqActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listagem().setVisible(true);
                
            }
        });
        
        table(lista);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deletar;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Pesq;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable lista;
    private javax.swing.JTextField nomePesq;
    // End of variables declaration//GEN-END:variables
}
